SUPPORT_SITE = 'YOUR REDMINE URI'
SUPPORT_API_KEY = 'SUPERVISOR API YOUR REDMINE'
SUPPORT_VERSION = 'YOUR REDMINE VERSION'
PROJECT_ID_FOR_NEW_ISSUE = 'ID YOUR PROJECT WHERE BE CREATED NEW ISSUES'  # IN INTEGER
BOT_TOKEN = 'BOT TOKENN'
AD_SERVER = 'YOUR ACTIVE DIRECTIRY SERVER'  # SAMPLE: ad.test.local
AD_SERVER_DN = 'YOUR ACTIVE DIRECTIRY'  # SAMPLE: dc=test,dc=local
username_ad_adm = 'USERNAME YOUR AD ADM'
passwd_ad_adm = 'PASSWD YOUR AD ADM'
member_of_for_ad_search = 'GROUP IN AD,USERS FROM WHICH CAN CREATE ISSUES VIA THIS BOT'  # SAMPLE: CN=admins,CN=Users,DC=test,DC=local
HELP_TEXT_FOR_BOT = "YOUR HELP TEXT FOR BOT"
